# Generated by Django 4.1.2 on 2022-11-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_alter_business_userid_alter_event_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='id',
            new_name='eventId',
        ),
    ]
