# Generated by Django 4.1.2 on 2022-11-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_rename_id_event_eventid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='name',
        ),
    ]
