# Generated by Django 4.1.2 on 2022-11-04 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_rename_businessname_business_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('USER_APPLIED', 'User Applied'), ('USER_ADMITTED', 'User Admitted'), ('TOKENS_REQUESTED', 'Tokens Requested'), ('TOKENS_CLAIMED', 'Tokens Claimed')], max_length=60)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.event')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.volunteer')),
            ],
        ),
    ]
