# Generated by Django 4.1.2 on 2022-11-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0006_userevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEvent',
            new_name='VolunteerEvent',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='currentTier',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='tokenBalance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
