# Generated by Django 4.1.2 on 2022-11-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0009_remove_event_confirmedvolunteers_volunteereventb'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confirmedVolunteers',
            field=models.ManyToManyField(blank=True, to='tokens.volunteer'),
        ),
    ]
