# Generated by Django 4.1.2 on 2022-11-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0010_event_confirmedvolunteers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolunteerEventB',
        ),
    ]
