# Generated by Django 4.1.2 on 2022-11-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0011_delete_volunteereventb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerevent',
            name='state',
            field=models.CharField(choices=[('USER_APPLIED', 'User Applied'), ('USER_ADMITTED', 'User Admitted'), ('TOKENS_REQUESTED', 'Tokens Requested'), ('TOKENS_APPROVED', 'Tokens Approved'), ('TOKENS_CLAIMED', 'Tokens Claimed')], default='USER_ADMITTED', max_length=50),
        ),
    ]
