# Generated by Django 4.1.2 on 2022-11-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0013_alter_volunteer_tokenbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='hoursLastWeek',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='hoursThisWeek',
            field=models.IntegerField(default=0),
        ),
    ]
